# Generated by Django 4.2.5 on 2023-10-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_stocks_options_rename_staff_product_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
