# Generated by Django 4.2.5 on 2023-10-13 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='note',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='income',
            name='inCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.incomecategory'),
        ),
    ]
